# Generated by Django 6.0 on 2026-01-27 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdPerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField(db_index=True, verbose_name='Tanggal Data')),
                ('account_name', models.CharField(max_length=255)),
                ('industry', models.CharField(blank=True, choices=[('Fashion', 'Fashion'), ('Beauty', 'Beauty'), ('FMCG', 'FMCG'), ('Electronics', 'Electronics'), ('Other', 'Other')], max_length=50, null=True)),
                ('campaign_objective', models.CharField(choices=[('Traffic', 'Traffic'), ('Sales', 'Sales')], max_length=50)),
                ('impressions', models.PositiveIntegerField()),
                ('reach', models.PositiveIntegerField()),
                ('clicks', models.PositiveIntegerField()),
                ('link_clicks', models.PositiveIntegerField()),
                ('content_views', models.PositiveIntegerField(default=0)),
                ('add_to_cart', models.PositiveIntegerField(default=0)),
                ('purchases', models.PositiveIntegerField(default=0)),
                ('purchase_value', models.DecimalField(decimal_places=2, default=0.0, max_digits=19)),
                ('amount_spent', models.DecimalField(decimal_places=2, default=0.0, max_digits=19)),
            ],
            options={
                'verbose_name': 'Kinerja Iklan',
                'verbose_name_plural': 'Data Kinerja Iklan',
                'indexes': [models.Index(fields=['account_name', 'created_date'], name='ads_analyze_account_2847af_idx')],
            },
        ),
    ]
