# Generated by Django 6.0 on 2026-01-28 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ads_analyzer', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='adperformance',
            unique_together={('created_date', 'account_name', 'campaign_objective')},
        ),
    ]
